name: Run Tests

on:
  schedule:
    - cron: '30 7 * * 4'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Test Dependencies
      run:  sudo apt install -y fq bats

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Tests
      run:  bats test/
